# Introduction to Machine Learning Pre-class assignment 3 Utilization of Object Orientation
## Name: Nguyen Anh Hoang Phuc

## Problem 1

## Problem 1: Enumeration of classes used so far
Now, you know that you must instantiate a class when you use it, and you know how to name a class. Based on this information, please answer what classes you have seen in the code you have used in previous assignments.


Find one or more each from Pandas, matplotlib, and scikit-learn.
### Method

After instantiation, you can execute methods such as scaler.fit(X). The fit method of StandardScaler has the ability to calculate the mean and standard deviation which will be used later for scaling.​

### Instance variable (attribute)

Thefit method has computed the mean and standard deviation, but there is no apparent change. However, inside the scaler instance, the calculation results are stored. These instances that store values are called instance variables or attributes. Here, the mean is stored inscaler.mean_and the variance, which is the squared value of the standard deviation, is storedscaler.var_.


The following print statement can be used to output the data.

```python
print("平均 : {}".format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]
print("分散 : {}".format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]
```
### Method and instance variable naming method
As with functions, methods and instance variables are named in all lowercase letters. Put an underscore when connecting words

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("mean :", scaler.mean_)
print("variance :", scaler.var_)
X_std = scaler.transform(X)

mean : [4.86 3.31 1.45 0.22]
variance : [0.0764 0.0849 0.0105 0.0056]


### Pandas:
<li> DataFrame

### matplotlib

<li> pyplot

### scikit-learn

<li> LinearRegression()
<li> StandardScaler
<li> DecisionTreeRegressor
<li> RandomForestRegressor
<li> SVR

## Problem 2

Please explain what kind of method and instance variable were used in the code that you have used in the previous assignments.


Please answer at least 5 of each.


**《Ndarray and str are also instances》**


When it comes to dotting, you have probably usedndarray.shapeandndarray.sum() for NumPy's ndarray many times. This means that ndarray is also an instance object,shapeis an instance variable, and sumis a method.


Any data that appears in Python code is an instance object, and list and str also have methods.


**The kinds of method and instance variable in the code used in the previous exercises are:**

**Methods**

1. pandas.loc()
2. pandas.iloc()
3. numpy.sum()
4. numpy.reshape()
5. numpy.ravel()

**Instance variable**

1. ndarray.shape
2. ndarray.ndim
3. ndarray.dtype
4. ndarray.size
5. ndarray.data

## Problem 3

In [2]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X,axis=0)
        self.var_ = np.var(X,axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            Feature value
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_)/self.var_
        return X_scaled

In [3]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Average : {}".format(scratch_scaler.mean_))
print("Dispersed : {}".format(scratch_scaler.var_))
X_std= scratch_scaler.transform(X)
print(X_std)

Average : [4.86 3.31 1.45 0.22]
Dispersed : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


## Problem 4

In [4]:
def type_judge(value_to_judge):
    if not isinstance(value_to_judge, (int,float)):
        print("Please input only numbers")
        return False
    else:
        return True

class ArthClass():
        
    def __init__(self, value):
        if(type_judge(value)):
            self.value = value
            print("Initial value {} set".format(self.value))
        else:
            self.value = value
        
    def add(self, value):
        
        if type_judge(self.value) and type_judge(value):
            self.value += value
        else:
            self.value = "can not be calculated because one of the values is not a number"
        
    def sub(self, value):
        
        if type_judge(self.value) and type_judge(value):
            self.value -= value
        else:
            self.value = "can not be calculated because one of the values is not a number"
            
    def mult(self, value):
        
        if type_judge(self.value) and type_judge(value):
            self.value *= value
        else:
            self.value = "can not be calculated because one of the values is not a number"
    
    def div(self, value):
        
        if type_judge(self.value) and type_judge(value):
            self.value /= value
        else:
            self.value = "can not be calculated because one of the values is not a number"
        
example = ArthClass(5)
print("value : {}".format(example.value))
example.add(3)
print("addition value : {}".format(example.value))

example2 = ArthClass("k")
example2.sub(3)
print("subtraction value : {}".format(example2.value))

example.mult(3)
print("multiplication value : {}".format(example.value))
example.div("k")
print("division value : {}".format(example.value))

Initial value 5 set
value : 5
addition value : 8
Please input only numbers
Please input only numbers
subtraction value : can not be calculated because one of the values is not a number
multiplication value : 24
Please input only numbers
division value : can not be calculated because one of the values is not a number
